production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    solr_home: /my/ruby/odms/solr
    path: /solr/production

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    solr_home: /Users/jakewendt/github_repo/ccls/odms/solr
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    solr_home: /Users/jakewendt/github_repo/ccls/odms/solr
    path: /solr/test
