-
  :attribute: :study_subject_id
  :uniqueness: true
  :allow_nil: true

-
  :attribute: :sample_outcome_on
  :presence: true
  :if: :sample_outcome?

-
  :attribute: :interview_outcome_on
  :presence: true
  :if: :interview_outcome?

-
  :attributes:
  - :interview_outcome_on
  - :sample_outcome_on
  :complete_date: true
  :allow_nil: true

-
  :attribute: :interview_outcome
  :allow_blank: true
  :inclusion:
    :in: <%= HomexOutcome.const_get :VALID_INTERVIEW_OUTCOMES %>

-
  :attribute: :sample_outcome
  :allow_blank: true
  :inclusion:
    :in: <%= HomexOutcome.const_get :VALID_SAMPLE_OUTCOMES %>

