-
  :attribute: :study_subject_id
  :uniqueness: true
  :allow_nil: true

-
  :attribute: :sample_outcome_on
  :presence: true
  :if: :sample_outcome_id?

-
  :attribute: :interview_outcome_on
  :presence: true
  :if: :interview_outcome_id?

-
  :attributes:
  - :interview_outcome_on
  - :sample_outcome_on
  :complete_date: true
  :allow_nil: true

