-
  :attribute: :has_irb_waiver
  :inclusion:
    :in: [ true, false ]

-
  :attribute: :organization_id
  :presence: true
  :uniqueness: true
#  :allow_blank: true
#	again, why presence and allow_blank?
#	this was to stop multiple error messages when blank

-
  :attribute: :organization
  :presence: true
  :if: :organization_id
