-
  :attribute: :event_category
  :presence: true
  :length:
    :in: !ruby/range 4..250

# http://stackoverflow.com/questions/3337020/how-to-specify-ranges-in-yaml

#	http://codereview.stackexchange.com/questions/159/use-of-a-regex-stored-inside-yaml-file
#	  email_regex: !ruby/regexp '/^([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})$/i'
