-
  :attribute: :path
  :length:
    :minimum: 1
  :uniqueness: true
  :format:
    :with: !ruby/regexp /^\//

-
  :attribute: :menu_en
  :uniqueness: true
  :length:
    :minimum: 4

-
  :attributes: 
  - :title_en
  - :body_en
  :length:
    :minimum: 4
