-
  :attribute: :path
  :length:
    :minimum: 1
  :uniqueness: true
  :format:
    :with: !ruby/regexp '/^\//'

-
  :attribute: :menu_en
  :uniqueness: true
  :length:
    :minimum: 4

-
  :attributes: 
  - :title_en
  - :body_en
  :length:
    :minimum: 4

# http://stackoverflow.com/questions/3337020/how-to-specify-ranges-in-yaml

#	http://codereview.stackexchange.com/questions/159/use-of-a-regex-stored-inside-yaml-file
#	  email_regex: !ruby/regexp '/^([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})$/i'
