
-
  :attributes:
  - :began_on
  - :ended_on
  :complete_date: true
  :allow_nil: true

-
  :attributes: :eligibility_criteria
  :length:
    :maximum: 65000
  :allow_blank: true

-
  :attributes: :label
  :presence: true
  :uniqueness: true
  :length:
    :maximum: 250

-
  :attribute: :key
  :format:
    :with: !ruby/regexp /\A\w+\z/
    :message: "Key can only contain alphanumerics and the underscore characters."
  :allow_blank: true


