-
  :attributes: :organization_id
  :presence: true

- 
  :attributes: :organization
  :presence: true
  :if: :organization_id

-
  :attributes: :other_organization
  :presence: true
  :if: :organization_is_other?

