-
  :attributes:
  - :code
  - :name
  - :fips_state_code
  :presence: true
  :uniqueness: true
  :length:
    :maximum: 250

-
  :attribute: :fips_country_code
  :presence: true
  :length:
    :maximum: 250
