class RecreateAbstracts < ActiveRecord::Migration
  def change


#	This is still VERY incomplete!!!


    create_table :abstracts do |t|
			t.string :bma07_classification
			t.date   :bma07_date_of_test
			t.string :bma07_found
			t.string :bma07_inconclusive_results
			t.string :bma07_percentage_of_blasts
			t.string :bma14_classification
			t.date   :bma14_date_of_test
			t.string :bma14_found
			t.string :bma14_inconclusive_results
			t.string :bma14_percentage_of_blasts
			t.string :bma28_classification
			t.date   :bma28_date_of_test
			t.string :bma28_found
			t.string :bma28_inconclusive_results
			t.string :bma28_percentage_of_blasts
			t.text   :bma_comments
			t.date   :bma_date_of_test
			t.string :bma_found
			t.string :bma_percentage_blasts
			t.string :bma_percentage_blasts_unknown
			t.text   :bmb_comments
			t.date   :bmb_date_of_test
			t.string :bmb_found
			t.string :bmb_percentage_blasts
			t.string :bmb_percentage_blasts_unknown
			t.date   :cbc_date_of_test
			t.string :cbc_found
			t.string :cbc_hemoglobin
			t.string :cbc_leukocyte_count
			t.string :cbc_number_of_blasts
			t.string :cbc_percentage_blasts
			t.string :cbc_platelet_count
			t.text   :clinical_diagnosis
			t.text   :conventional_karyotyping_results
			t.string :cp_found
			t.date   :cs_date_of_test
			t.string :cs_found
			t.string :csf_blasts_present
			t.text   :csf_cytology
			t.date   :csf_date_of_test
			t.string :csf_found
			t.string :csf_number_of_blasts
			t.string :csf_pb_contamination
			t.string :csf_rbc
			t.string :csf_wbc
			t.date   :cxr_date_of_test
			t.string :cxr_found
			t.text   :cxr_mediastinal_mass_description
			t.date   :dfc_date_of_test
			t.string :dfc_found
			t.date   :ds_date_of_test
			t.string :ds_found
			t.string :height_in_cm
			t.string :height_in_in
			t.date   :hla_date_of_test
			t.string :hla_found
			t.text   :hla_results
			t.text   :hospital_fish_results
			t.date   :hpr_date_of_test
			t.string :hpr_found
			t.string :hyperdiploidy_number_of_chromosomes
			t.string :induction_protocol_name_and_number
			t.string :marker_bmk
			t.string :marker_bml
			t.string :marker_cd10
			t.string :marker_cd11b
			t.string :marker_cd11c
			t.string :marker_cd13
			t.string :marker_cd14
			t.string :marker_cd15
			t.string :marker_cd16
			t.string :marker_cd19
			t.string :marker_cd19_cd10
			t.string :marker_cd1a
			t.string :marker_cd2
			t.string :marker_cd20
			t.string :marker_cd21
			t.string :marker_cd22
			t.string :marker_cd23
			t.string :marker_cd24
			t.string :marker_cd25
			t.string :marker_cd3
			t.string :marker_cd33
			t.string :marker_cd34
			t.string :marker_cd38
			t.string :marker_cd3_cd4
			t.string :marker_cd3_cd8
			t.string :marker_cd4
			t.string :marker_cd40
			t.string :marker_cd41
			t.string :marker_cd45
			t.string :marker_cd5
			t.string :marker_cd56
			t.string :marker_cd57
			t.string :marker_cd61
			t.string :marker_cd7
			t.string :marker_cd71
			t.string :marker_cd8
			t.string :marker_cd9
			t.string :marker_cdw65
			t.text   :marker_comments
			t.string :marker_glycophorin_a
			t.string :marker_hla_dr
			t.string :marker_igm
			t.string :marker_sig
			t.string :marker_tdt
			t.string :other_all_leukemia_class
			t.string :other_aml_leukemia_class
			t.text   :other_markers
			t.date   :ploidy_date_of_test
			t.string :ploidy_found
			t.string :ploidy_found_in_cytometry
			t.string :ploidy_found_separately
			t.date   :tdt_date_of_test
			t.string :tdt_found
			t.string :tdt_found_in_cytometry
			t.string :tdt_found_separately
			t.string :tdt_negative
			t.string :tdt_numerical_result
			t.string :tdt_positive
			t.text   :therapeutic_agents
			t.string :weight_in_kg
			t.string :weight_in_lb	
      t.timestamps
    end
  end
end
